### PR TITLE
Updated PostCSS, and added warning when variable cannot be resolved along with option to turn warning on or off ('warnOfUnresolved'). Upped version. Etc.

### PR DESCRIPTION
**Pull request by mjschlot**
- Updated postcss dependency to 6
- Made required updates due to upgrade to version 6
- Added the new postcss 'results' parameter so I can add warnings (via results.warn(..))
- Added option 'warnOfUnresolved' and defaulted to true.
- Documented new option.
- Updated the version to 2.0.0. since the update of postcss dependency
- Updated eslint, and postcss-scss to newest versions
- Added "postcss-reporter" as dev dependency so we can see postcss warnings when runing tests. Helpful when resolving some bugs uncovered when I started reporting warnings that were not obvious before, and also helpful when resolving issues resulting from upgrading postcss
- Added and documented support for `variables` being a function instead of an object

### CODE REVIEW

**Comment by mjschlot** [comment]
Hi @jonathantneal 
Do you believe you will have time to merge this change before end of year? I'm planning some changes to my team's use of PostCSS and knowing timing would be helpful.
Thanks!

**Comment by deemstone** [comment]
Seems a little complex. Transparent `result` through the functions calls. Make this PR looks not  relieved.

**Comment by jonathantneal** [comment]
There is _a lot_ going on in this PR. My thoughts are:

1. we need more maintainers for this project.
2. we need a maintainer for precss.

Actually, I stopped maintaining precss almost immediately after it was released, going as far as to not follow the project. I am just now seeing how many issues it has and how popular it remains despite that — which makes no sense to me.

This is a lot to take in.

**Comment by mjschlot** [comment]
@deemstone Yes, passing `result` around is not my preferred solution either, but other solutions would require a more significant rewrite, and this is what works with the current coding -- and the current coding is good and I see no reason to do a larger rewrite.

@jonathantneal  I agree. It is a lot. There are a few extras but 95% of it was mandatory to accomplish adding warnings via postcss 6's new API, or were directly the results of upgrading to postcss 6. The other 5% are things myself and my team really wanted to see (e.g. warnings on unresolved variables). With this larger commit merged in future PRs can be much smaller to add some new features and fixes. But this larger PR seems unavoidable to get postcss-advanced-variables upgrade to postcss 6.

How can I help get this merged and help maintain postcss-advanced-variables? I don't have the time to help with precss, but I can help with this postcss-advanced-variables if you want.

**Comment by mjschlot** [comment]
Thanks @jonathantneal . Now that it is merged in, can it be published to NPM?

**Pull request merged**
