### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by jonathantneal**
- Completely rewritten
- Added: `unresolved` option to throw errors or warnings on unresolved variables
- Added: Support for the `#{$var}` syntax
- Added: Support for iterators in `@each` at-rules
  (`@each $item $index in $array`)
- Added: Support for variable replacement in all at-rules
- Fixed: Number comparison in `@if` at-rules

### CODE REVIEW

**Comment by mjschlot** [comment]
Wow! You have been busy. This is some fantastic work!

**Comment by lkraav** [comment]
Thanks @jonathantneal and hny18. Does precss need anything other than a `package.json` bump for this?

**Comment by jonathantneal** [comment]
I’m working on precss this morning. With the v2 major bump came all the improvements to existing features, but I’ve just released [v2.1.0](https://github.com/jonathantneal/postcss-advanced-variables/blob/master/CHANGELOG.md#210-january-1-2018) which adds support for `@mixin`, `@include`, and `@content`. I may want to release another significant feature later today — more on that:

For those less familiar with PostCSS Plugins; I can’t yet rely on other plugins to manage variable-reliant features for me because they run sequentially and not in parallel. As a result, one plugin might resolve variables and the next plugin might attempt to use a mixin that leverages those now-missing variables. Or vice-versa; one plugin might throw for unresolved variables that would be coming from the mixin not yet transformed.

Because of this, I will probably, unfortunately need to transform `@import` too, if I want things like `@import "dir/$name"` to work. Thankfully, I’ve already written [a specification for sass import behavior](https://jonathantneal.github.io/sass-import-resolve/) and I have [published a module to resolve the filename and contents of sass imports](https://github.com/jonathantneal/sass-import-resolve), so the remaining work _seems_ minimal.

At that point, if I add just one more sassy feature — `@extend` support — then this plugin handles all general sass-like behavior. Except... [many developers do not like sassy `@extend`](https://tiffanybbrown.com/2017/03/dont-use-extend-sass/index.html), so maybe I would not want to do that.

Okay, so, where would this leave precss? precss would get all the improvements in v2.1.0 or v2.2.0 (with sassy `@import`), and it would keep the additional syntactical sugar (like `@at-root` and `@property-lookup`), and it would keep the future cssnext-like functionality. I would probably switch the cssnext-like functionality to just use [postcss-preset-env](https://github.com/jonathantneal/postcss-preset-env) so that you could have a controllable hybrid of sass features and future spec features.

**Comment by mjschlot** [comment]
With PostCSS the order that plugins are ran is obviously important. We use postcss-advanced-variables with other plugins. As long as postcss-advanced-variables is ran early in the processing change, it all works well. For mixins we use `postcss-mixins` now.

Any feature that would modifying the value of a variable (e.g. a loop) likely does need to be built in, but `@mixin`, `@import` and etc should not need to be built in. I'd be interested in knowing what issues are you running into which requires building these features into postcss-advanced-variables so?

**Comment by rickymetz** [comment]
Just discovered this library and I'm loving it

>At that point, if I add just one more sassy feature — @extend support — then this plugin handles all general sass-like behavior.

`@extend` would be a dream! I use it all the time as the mention in your linked example with `%placeholder` classes!

**Pull request merged**
